name: Report coverage

on: [push, workflow_dispatch]

jobs:

  # Report code coverage to Codecov.
  coverage:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            python: ["3.10", "3.11-dev"]

    steps:
      - name: Check out code.
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python }}

      - name: Install package.
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[test]

      - name: Measure code coverage.
        run: pytest --cov --cov-report xml

      - name: Upload coverage report.
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
